# Generated by Django 4.1.7 on 2023-05-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licencia', '0002_licencias_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencias',
            name='motivo',
            field=models.CharField(choices=[('N', 'Nuevo'), ('R', 'Renovacion'), ('A', 'Ampliacion')], default='N', max_length=100),
        ),
    ]
