# Generated by Django 4.1.7 on 2023-05-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licencia', '0003_alter_licencias_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencias',
            name='motivo',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Renovacion', 'Renovacion'), ('Ampliacion', 'Ampliacion')], default='Nuevo', max_length=100),
        ),
    ]
