# Generated by Django 4.1.7 on 2023-05-31 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Licencia', '0004_alter_licencias_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencias',
            name='id_usuario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
